### ISSUE TITLE
Always SIGNATURE_INCORRECT

### ISSUE THREAD

**Issue by MarkKhramko** [cretueusebiu/gamecenter-identity-verifier#1]
Hi! I'm on iOS 10.1 authenticated in GameCenter debug mode on my iPhone 5S. But I could not get your framework to work. The result of verification is always false and error "3" (SIGNATURE_INCORRECT).

**Comment by cretueusebiu** [comment]
Make sure the signature and salt are binary strings.

Or try this one: https://gist.github.com/cretueusebiu/3d18629110281aec043a0848e1761c3f 
In this one the salt and signature must be base64 encoded.

Usage:

```php
$verifier = (new IdentityVerifier())
    ->playerId('G:1111111111')
    ->timestamp('1469626352131')
    ->certificate('https://static.gc.apple.com/public-key/gc-prod-2.cer')
    ->bundleId('com.myapp.dev')
    ->salt(base64_decode('...'))
    ->signature(base64_decode('...'));

if ($verifier->verify()) {
    // success
} else {
    var_dump($verifier->lastErrorCode());
}
```

**Comment by MarkKhramko** [comment]
Oh my God thanks! base64_decode did it! You better add this as a hint to README :)

**Comment by cretueusebiu** [comment]
I'll have to update it with the  one from the gist.

**Comment by MarkKhramko** [comment]
If you want to. I used the old code.
